#include "io/RailMLParser.h"
#include "simulation/InitialParameters.h"
#include "util/portability.h"  // localtime_r shim on MSVC
static zmq::context_t ctx;

extern InitialParameters initial_variables;

namespace {
bool loadRttpDocument(const std::string& payload, pugi::xml_document& document) {
	const pugi::xml_parse_result result = document.load_buffer(payload.data(), payload.size());
	if (result)
		return true;
	std::cerr << "RTTP XML parse error at byte " << result.offset << ": " << result.description()
			  << "; payload starts with " << payload.substr(0, 120) << "\n";
	return false;
}
}

void read_rttp_train_view(std::string rttp) {
	pugi::xml_document rttp_doc;
	if (!loadRttpDocument(rttp, rttp_doc))
		return;
	pugi::xml_node trainView = rttp_doc.child("rTTP").child("rTTPTrainView");
	int train_counter = 0;

	for (pugi::xml_node train = trainView.child("rTTPForSingleTrain"); train; train = train.next_sibling("rTTPForSingleTrain")) {
		std::cout << "Train " << train.attribute("trainID").value() << "\n";
		for (pugi::xml_node section = train.child("tDSectionOccupation"); section; section = section.next_sibling("tDSectionOccupation")) {
			std::cout << " in Section " << section.attribute("tDSectionID").value() << "\n";
			std::cout << " trainID " << section.attribute("trainID").value() << "\n";
			std::cout << " occupation starting at " << section.attribute("occupationStart").value() << "\n";
			std::cout << " routeID " << section.attribute("routeId").value() << "\n";
		}
	}
}
void read_rttp_infra_view(std::string rttp) {
	pugi::xml_document rttp_doc;
	if (!loadRttpDocument(rttp, rttp_doc))
		return;
	pugi::xml_node trainView = rttp_doc.child("rTTP").child("rTTPInfrastructureView");
	int train_counter = 0;

	for (pugi::xml_node train = trainView.child("rTTPForSingleTDSection"); train; train = train.next_sibling("rTTPForSingleTDSection")) {
		std::cout << "tDSectionId " << train.attribute("tDSectionId").value() << "\n";
		for (pugi::xml_node section = train.child("tDSectionOccupation"); section; section = section.next_sibling("tDSectionOccupation")) {
			std::cout << " in Section " << section.attribute("tDSectionID").value() << "\n";
			std::cout << " trainID " << section.attribute("trainID").value() << "\n";
			std::cout << " occupation starting at " << section.attribute("occupationStart").value() << "\n";
			std::cout << " routeID " << section.attribute("routeId").value() << "\n";
		}
	}
}

// Prepare TSM file to send
std::string trafficStateMonitoring_xml(nlohmann::json jsmsg) {
	/*
	creates the TSM file used to populate the traffic state to external modules
	*/

	std::stringstream ss;
	// this is the simulation time to use in XML, since it is not the current time equal to simulation time
	// It is equal to 3600*H where H is the start of timetable e.g. 07:00==> 3600*7=25200 seconds
	int startingSimulationTime = 23300; // 25200; 23300=>06:28:20

	time_t now = time(0);
	time_t production_time = now;

	struct tm ltm, prtm, stime;
	localtime_r(&now, &ltm);

	now = now - ((ltm.tm_hour * 3600) + (ltm.tm_min * 60) + ltm.tm_sec) + startingSimulationTime;
	time_t simulation_time = now + static_cast<long>(jsmsg["time"]);
	localtime_r(&now, &ltm); // recalculate on new time
	localtime_r(&simulation_time, &stime);
	localtime_r(&production_time, &prtm); // keep this for the comment of thexml file

	pugi::xml_document doc;
	// Generate XML declaration
	auto declarationNode = doc.append_child(pugi::node_declaration);
	declarationNode.append_attribute("version") = "1.0";
	declarationNode.append_attribute("encoding") = "UTF-8";
	declarationNode.append_attribute("standalone") = "yes";

	pugi::xml_node comment = doc.append_child(pugi::node_comment);
	std::string commentsign;
	char currTime[100];
	strftime(currTime, 50, "%Y-%m-%d %H:%M:%S", &prtm);
	commentsign = "Generated by EGTRAIN on ";
	commentsign += currTime;
	comment.set_value(commentsign.c_str());

	// tag::code[]
	// add Node with some name
	auto root = doc.append_child("trafficState");
	char simTime[100]; // simulation time
	strftime(simTime, 50, "%Y-%m-%d %H:%M:%S.000 CEST", &stime);

	root.append_attribute("currentTime") = simTime; // "2013-02-21 01:02:00.000 CEST";

	// add active trains' traffic state
	for (auto it = jsmsg["trains"].begin(); it != jsmsg["trains"].end(); ++it) {
		if (it.value()["inArea"] == 1) {
			// for (auto it2 = it.value().begin(); it2 != it.value().end(); ++it2) {
			//     if (it2["inArea"] == 1) {
			pugi::xml_node trainStateInArea = root.append_child("trainStateInArea");

			pugi::xml_node trainID = trainStateInArea.append_child("trainID");
			trainID.append_attribute("trainNumber") = it.key().c_str();

			pugi::xml_node trainPosition = trainStateInArea.append_child("trainPosition");
			std::string trackID = it.value()["trackID"];
			trainPosition.append_attribute("trackID") = trackID.c_str();
			if (it.value()["direction"] == false) {
				trainPosition.append_attribute("travelDirection") = "1";
			} else
				trainPosition.append_attribute("travelDirection") = "-1";

			trainPosition.append_attribute("posOnTrack") = to_string(it.value()["km-point"]).c_str();
			std::string BlockOccupied = it.value()["BlockOccupied"];
			trainPosition.append_attribute("currentTrackVacancyDetectionSection") = BlockOccupied.c_str();
			if (it.value()["lastOccTime"] >= 0) {
				double aa = it.value()["lastOccTime"];
				struct tm ltm2;
				time_t temp = now + static_cast<long>(it.value()["lastOccTime"]);

				localtime_r(&temp, &ltm2);
				char eventTime[100]; // event time
				strftime(eventTime, 50, "%Y-%m-%d %H:%M:%S.000 CEST", &ltm2);
				trainPosition.append_attribute("lastOccupationTime") = eventTime;
			}
			pugi::xml_node speed = trainStateInArea.append_child("speed");
			double vitesse = it.value()["speed"];
			speed.append_child(pugi::node_pcdata).set_value(std::to_string(vitesse).c_str());

			//  }
		} else {
			// add non-active trains' traffic state
			pugi::xml_node trainStateOutArea = root.append_child("trainStateOutArea");

			pugi::xml_node trainID = trainStateOutArea.append_child("trainID");

			trainID.append_attribute("trainNumber") = it.key().c_str();
			double depTime = it.value()["depTime"];
			struct tm ltm2;
			time_t temp = now + depTime;
			localtime_r(&temp, &ltm2);
			char eventTime[100]; // event time
			strftime(eventTime, 50, "%Y-%m-%d %H:%M:%S.000 CEST", &ltm2);
			trainID.append_attribute("expectedEntranceTime") = eventTime;
		}
	}

	doc.save(ss, "  ");
	return ss.str();
}

// Prepare route choice file to send
std::string routeChoice_xml(nlohmann::json jsmsg) {
	/*
	creates the TSM file used to populate the traffic state to external modules
	*/

	std::stringstream ss;

	// this is the simulation time to use in XML, since it is not the current time equal to simulation time
	// It is equal to 3600*H where H is the start of timetable e.g. 07:00==> 3600*7=25200 seconds
	int startingSimulationTime = 23300; // 25200; 23300=>06:28:20

	time_t now = time(0);
	time_t production_time = now;

	struct tm ltm, prtm, stime;
	localtime_r(&now, &ltm);

	now = now - ((ltm.tm_hour * 3600) + (ltm.tm_min * 60) + ltm.tm_sec) + initial_variables.startingSimulationTime;
	time_t simulation_time = now + static_cast<long>(jsmsg["time"]);
	localtime_r(&now, &ltm); // recalculate on new time
	localtime_r(&simulation_time, &stime);
	localtime_r(&production_time, &prtm); // keep this for the comment of thexml file

	pugi::xml_document doc;
	// Generate XML declaration
	auto declarationNode = doc.append_child(pugi::node_declaration);
	declarationNode.append_attribute("version") = "1.0";
	declarationNode.append_attribute("encoding") = "UTF-8";
	declarationNode.append_attribute("standalone") = "yes";

	pugi::xml_node comment = doc.append_child(pugi::node_comment);
	std::string commentsign;
	char currTime[100];
	strftime(currTime, 50, "%Y-%m-%d %H:%M:%S", &prtm);
	commentsign = "Generated by EGTRAIN on ";
	commentsign += currTime;
	comment.set_value(commentsign.c_str());

	// tag::code[]
	// add Node with some name
	auto root = doc.append_child("routeChoiceRequest");
	char simTime[100]; // simulation time
	strftime(simTime, 50, "%Y-%m-%d %H:%M:%S.000 CEST", &stime);

	root.append_attribute("currentTime") = simTime; // "2013-02-21 01:02:00.000 CEST";

	// add active trains' traffic state
	for (auto it = jsmsg["passengers"].begin(); it != jsmsg["passengers"].end(); ++it) {
		pugi::xml_node person = root.append_child("person"); //<person>
		std::string person_id = it.key().c_str();
		std::string trip_id = "1";
		person.append_attribute("person_id") = person_id.c_str(); // person_id=
		person.append_attribute("trip_id") = trip_id.c_str();	  // trip_id=

		pugi::xml_node origin = root.append_child("origin");
		std::string origin_station = it.value()["origin"];
		origin.append_child(pugi::node_pcdata).set_value(origin_station.c_str()); //<origin>

		pugi::xml_node destination = root.append_child("destination");
		std::string destination_station = it.value()["destination"];
		destination.append_child(pugi::node_pcdata).set_value(destination_station.c_str()); //<destination>

		pugi::xml_node departure_time = root.append_child("departure_time");
		int departure_time_station = it.value()["departure_time"];
		departure_time.append_child(pugi::node_pcdata).set_value(std::to_string(departure_time_station).c_str()); //<departure_time>
	}

	doc.save(ss, "  ");
	return ss.str();
}

int send_traffic_state5555(nlohmann::json jsmsg, std::string TSM) {
	zmq::socket_t sock(ctx, zmq::socket_type::req);

	// try {
	sock.connect("tcp://127.0.0.1:5555");

	// throw(0);
	// }
	// catch (int error) {
	//     std::cout << "error";
	//    return error;
	// }

	std::string a = TSM; // "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><!--Generated by EGTRAIN on 2022-12-19 16:45:18--><trafficState currentTime=\"2022-12-19 07:00:00.000 CEST\">	<trainStateInArea>		<trainID trainNumber=\"0\" />		<trainPosition trackID=\"1000\" travelDirection=\"1\" posOnTrack=\"1000km\" currentTrackVacancyDetectionSection=\"1000\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"1\" />		<trainPosition trackID=\"1001\" travelDirection=\"1\" posOnTrack=\"1001km\" currentTrackVacancyDetectionSection=\"1001\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"2\" />		<trainPosition trackID=\"1002\" travelDirection=\"1\" posOnTrack=\"1002km\" currentTrackVacancyDetectionSection=\"1002\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"3\" />		<trainPosition trackID=\"1003\" travelDirection=\"1\" posOnTrack=\"1003km\" currentTrackVacancyDetectionSection=\"1003\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"4\" />		<trainPosition trackID=\"1004\" travelDirection=\"1\" posOnTrack=\"1004km\" currentTrackVacancyDetectionSection=\"1004\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"5\" />		<trainPosition trackID=\"1005\" travelDirection=\"1\" posOnTrack=\"1005km\" currentTrackVacancyDetectionSection=\"1005\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"6\" />		<trainPosition trackID=\"1006\" travelDirection=\"1\" posOnTrack=\"1006km\" currentTrackVacancyDetectionSection=\"1006\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"7\" />		<trainPosition trackID=\"1007\" travelDirection=\"1\" posOnTrack=\"1007km\" currentTrackVacancyDetectionSection=\"1007\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"8\" />		<trainPosition trackID=\"1008\" travelDirection=\"1\" posOnTrack=\"1008km\" currentTrackVacancyDetectionSection=\"1008\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"9\" />		<trainPosition trackID=\"1009\" travelDirection=\"1\" posOnTrack=\"1009km\" currentTrackVacancyDetectionSection=\"1009\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateOutArea>		<trainID trainNumber=\"0\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"1\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"2\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"3\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea></trafficState>";

	jsmsg["xml"] = a;
	zmq::message_t z_out(jsmsg.dump());
	std::cout << "\nSending:" << z_out.to_string();
	sock.send(z_out, zmq::send_flags::none);

	zmq::message_t z_in;
	(void)sock.recv(z_in);

	std::cout << "Received from 5555:" << z_in.to_string();

	return 1;
}

int send_traffic_state5556(nlohmann::json jsmsg, std::string TSM) {
	zmq::socket_t sock(ctx, zmq::socket_type::req);

	// try {
	sock.connect("tcp://127.0.0.1:5556");

	// throw(0);
	// }
	// catch (int error) {
	//     std::cout << "error";
	//    return error;
	// }

	std::string a = TSM; // "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><!--Generated by EGTRAIN on 2022-12-19 16:45:18--><trafficState currentTime=\"2022-12-19 07:00:00.000 CEST\">	<trainStateInArea>		<trainID trainNumber=\"0\" />		<trainPosition trackID=\"1000\" travelDirection=\"1\" posOnTrack=\"1000km\" currentTrackVacancyDetectionSection=\"1000\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"1\" />		<trainPosition trackID=\"1001\" travelDirection=\"1\" posOnTrack=\"1001km\" currentTrackVacancyDetectionSection=\"1001\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"2\" />		<trainPosition trackID=\"1002\" travelDirection=\"1\" posOnTrack=\"1002km\" currentTrackVacancyDetectionSection=\"1002\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"3\" />		<trainPosition trackID=\"1003\" travelDirection=\"1\" posOnTrack=\"1003km\" currentTrackVacancyDetectionSection=\"1003\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"4\" />		<trainPosition trackID=\"1004\" travelDirection=\"1\" posOnTrack=\"1004km\" currentTrackVacancyDetectionSection=\"1004\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"5\" />		<trainPosition trackID=\"1005\" travelDirection=\"1\" posOnTrack=\"1005km\" currentTrackVacancyDetectionSection=\"1005\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"6\" />		<trainPosition trackID=\"1006\" travelDirection=\"1\" posOnTrack=\"1006km\" currentTrackVacancyDetectionSection=\"1006\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"7\" />		<trainPosition trackID=\"1007\" travelDirection=\"1\" posOnTrack=\"1007km\" currentTrackVacancyDetectionSection=\"1007\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"8\" />		<trainPosition trackID=\"1008\" travelDirection=\"1\" posOnTrack=\"1008km\" currentTrackVacancyDetectionSection=\"1008\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateInArea>		<trainID trainNumber=\"9\" />		<trainPosition trackID=\"1009\" travelDirection=\"1\" posOnTrack=\"1009km\" currentTrackVacancyDetectionSection=\"1009\" lastOccupationTime=\"2010-01-11 06:04:59.0 CET\" />		<speed>True</speed>	</trainStateInArea>	<trainStateOutArea>		<trainID trainNumber=\"0\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"1\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"2\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea>	<trainStateOutArea>		<trainID trainNumber=\"3\" expectedEntranceTime=\"2010-01-11 06:34:30.0 CET\" />	</trainStateOutArea></trafficState>";

	jsmsg["xml"] = a;
	zmq::message_t z_out(jsmsg.dump());
	std::cout << "\nSending:" << z_out.to_string();
	sock.send(z_out, zmq::send_flags::none);

	zmq::message_t z_in;
	(void)sock.recv(z_in);

	std::cout << "Received from 5556:" << z_in.to_string();

	return 1;
}
